version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynomonitor
    command: sh -c "python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env

